language: node_js
node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

sudo: required

before_script:
  - docker pull selenium/standalone-firefox:2.48.2
  - docker pull selenium/standalone-chrome:2.48.2
  - docker images --no-trunc

install:
  - yarn install

script:
  - yarn run lint
  - yarn run test
  - dockers/Screenshotter/screenshotter.sh --verify

